# Password generator

import random

# this is use to generate the strong passcode whenever the user wants to generate the passcode
def generate_strong_passcode(length_of_password=12):
    """This function will suggest a strong password to the user according to the length of the password that the user wants to generate."""
    string1 = ""
    string2 = ""
    # Characters that we can use to create a strong password
    characters = (
        "abcdefghijklmnopqrstuvwxyz123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*_"
    )
    # For getting the strong passcode we use some special characters
    necessary_characters_in_the_password = "!@#$%^&*_"

    for i in range(0, (length_of_password - 3)):
        string1 = random.choice(
            characters
        )  # Random module has a function "choice" which Returns a random element from the given sequence.
        string2 += string1  # Concatenation of the string.
    for a in range(0, 3):
        string1 = random.choice(necessary_characters_in_the_password)
        string2 += string1
    # returning the password which was generated by the function.
    return string2

# this is use to suggest a strong passcode whenever the user wants the suggestion
def suggest_passcode_message():
    """This function will suggest a strong passcode and display it in a message box."""
    strong_passcode = generate_strong_passcode()
    messagebox.showinfo("Suggested Passcode", f"Suggested Passcode: {strong_passcode}")
    return strong_passcode